name: Continuous Integration

on: push

jobs:
  app:
    name: Continuous Integration (app)
    runs-on: ubuntu-20.04
    environment: production

    container:
      image: ruby:3.0-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add build-base curl-dev git nodejs
          apk add tar

      - name: Cache Gems
        uses: actions/cache@v2.1.3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install Gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Lint
        run: bundle exec rubocop --parallel --display-cop-names

      - name: Build
        run: bundle exec middleman build

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: build/
          target: /mnt/default/docker/volumes/nginx_http/_data/florian.dejonckhee.re/
          strip_components: 1
